module.exports = {
  MARKET_STATE: {
    ONGOING: 0,
    REVEALING: 1,
    ANNOUNCING: 2,
    FINISHED: 3
  },
  REVEAL_BLOCK_PERIOD: 24 * 3600 / 10,
  ANNOUNCE_BLOCK_PERIOD: 24 * 3600 / 10,
  MAX_DIGITS_PRECISION: 6
}
